name: dustrack
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7,<=3.13
  - pip
  - numpy<2
  - pandas
  - matplotlib
  - portion
  - ffmpeg-python
  - pytables
  - dill
  - tqdm
  - scikit-image
  - pip:
    - opencv-python
    - pysampled
    - decord
    - pyfilemanager
    - datanavigator>=1.1.3
